name: appfotajer
description: "تطبيق توصيل طلبات"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management (اختر واحدة: provider أو bloc)
  provider: ^6.1.1
  # flutter_bloc: ^9.1.1
  # Images
  image_picker: ^1.0.4
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.3.0
  # Backend
  appwrite: ^17.1.0
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  # Location & Maps
  geolocator: ^14.0.2

  permission_handler: ^12.0.1
  # Localization & Formatting
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  # UI & Utils
  google_fonts: ^6.3.0
  fluttertoast: ^8.2.2
  uuid: ^4.5.1
  font_awesome_flutter: ^10.10.0
  flutter_local_notifications: ^19.4.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_app.png"
  adaptive_icon_background: "assets/images/logo_app_background.png"
  adaptive_icon_foreground: "assets/images/logo_app_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash_logo.png"
  android_12: true